theme: jekyll-theme-minimal
title: The title of your site
description: A short description of your site's purpose
author:
  name: Adéla Šubrtová
  email: subrtade (at) fel.cvut.cz
header_pages:
  - about.md
