theme: jekyll-theme-minimal
title: Adéla Šubrtová
logo: /photo.jpeg
description: A short description of your site's purpose
author:
  name: Adéla Šubrtová
  email: subrtade (at) fel.cvut.cz
header_pages:
  - about.md
